### ISSUE TITLE
app generator fails when trying to get git name

### ISSUE THREAD

**Issue by Snorlock** [github/generator-hubot#15] opened 2014-12-11 21:07 UTC
/usr/local/lib/node_modules/generator-hubot/generators/app/index.js:72
      var userName = this.user.git.name();
                                   ^
TypeError: Property 'name' of object #<Object> is not a function
    at Base.yeoman.generators.Base.extend.prompting.askFor (/usr/local/lib/node_modules/generator-hubot/generators/app/index.js:72:36)
    at /usr/local/lib/node_modules/generator-hubot/node_modules/yeoman-generator/lib/base.js:381:14
    at processImmediate [as _immediateCallback] (timers.js:345:15)

I recieve this error when yo hubot.
But after iv removed the parenthasis after name and email, it works for me. Any reason for that?

**Comment by technicalpickles** [comment] 2015-02-21 21:54
I have yo 1.3.3 also, so and I don't see the problem :sweat: I was thinking it could be a different dependency, but generator-hubot's only yeoman dependency is yeoman-generator, and it's exact:

```
"yeoman-generator": "^0.17.0",
```

So, I can't reproduce this, but I can add an edge-case to support them just in case.

**Comment by technicalpickles** [comment] 2015-02-21 21:56
@Snorlock I release generator-hubot@0.2.4 with a fix for this if you want to give that a try.

**Comment by Snorlock** [comment] 2015-02-22 02:34
I will check when im back from India

**Comment by Snorlock** [comment] 2015-03-02 15:46
I can confirm it works now! Sweet!

**Comment by technicalpickles** [comment] 2015-03-02 15:49
Closing, thanks for confirming!

**Closed by technicalpickles** 2015-03-02 15:49 UTC
Labels: bug
